version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  backend:
    build: ./backend
    ports:
      - "4001:4000"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    links:
      - frontend
      - backend
